#!/bin/bash

source "$CONFIG_DIR"/colors.sh
source "$CONFIG_DIR"/icons.sh

# find documentation in https://www.josean.com/posts/sketchybar-setup

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
FONT="SF Pro" # Font used for the bar

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=26 blur_radius=30 

sketchybar --default icon.font="$FONT:Semibold:13.0"  \
                     icon.color=$WHITE                 \
                     label.font="$FONT:Semibold:13.0" \
                     label.color=$WHITE                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=6            \
                     background.height=22                  \
                     padding_left=4                        \
                     padding_right=4                      \
                     label.padding_left=5                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=5


# LEFT SIDE ITEMS

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# RIGHT SIDE ITEMS

source $ITEM_DIR/clock.sh
# source $ITEM_DIR/cpu.Sh
source $ITEM_DIR/keyboard.sh
# source $ITEM_DIR/weather.sh
source $ITEM_DIR/wifi.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
