import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]
[env]
TERM = 'xterm-256color'
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 14




