# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'

success_symbol = '[➜](bold green)' 
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[⌘](bold yellow)'
